Add details regarding abstract and virtual functions in traits
tact-lang/tact-docs pull request #207
Opened 2024-04-30 12:59 UTC by Oni-giri

Hi!

I noticed that the docs didn't include any mention of `virtual` and `abstract` functions in traits, which can be overridden in the implementation contract. The virtual keyword for functions can be seen in an example in the [Tact by Example](https://tact-by-example.org/05-your-own-trait) website, for instance.

This is a great feature of Tact, so I think it's worth it to include it in the official docs! I also added references to it in other pages which were relevant.

2024-05-02 06:16 UTC, anton-trunov requested changes

2024-05-02 06:16 UTC, anton-trunov commented on pages/book/contracts.mdx
> +Internal functions can access the contract's [persistent state variables](#variables) and [constants](#constants). If declared in a [traits](/book/types#traits), they can be declared as [virtual or a
This should be moved to the contract [structure](https://docs.tact-lang.org/book/contracts#structure) subsection. There is this sentence there:

> Furthermore, contracts can inherit all the declarations from [traits](https://docs.tact-lang.org/book/types#traits) and override some of their default behaviours.

2024-05-02 06:16 UTC, anton-trunov commented on pages/book/functions.mdx
> +        return true;
The following way to express the same meaning is idiomatic:
```suggestion
        return sender() != self.owner;
```

2024-05-02 06:17 UTC, anton-trunov commented
@Oni-giri Thanks for your contribution! Let's fix a couple of nits and we are good to go

2024-05-07 06:29 UTC, anton-trunov approved these changes, later dismissed

2024-05-07 08:25 UTC, anton-trunov commented
@novusnota check my recent changes please

2024-05-07 12:07 UTC, novusnota approved these changes
Looks nice, will be helpful towards #131

2024-05-07 12:21 UTC, merged