Fix typo and the content
tact-lang/tact-docs pull request #27
Opened 2023-10-27 07:58 UTC by howardpen9

2023-10-27 09:45 UTC, anton-trunov requested changes

2023-10-27 09:45 UTC, anton-trunov commented on pages/_meta.json
> +    "title": "Getting Start",
"getting started" is correct

2023-10-27 09:45 UTC, anton-trunov commented on pages/index.mdx
> -- [Getting Started](/start)
same here

2023-10-27 09:45 UTC, anton-trunov commented on pages/language/guides/functions.mdx
> +  Native functions could be also mutable and extension one
```suggestion
  Native functions could be also mutable and extension ones
```

2023-10-27 09:45 UTC, anton-trunov commented on pages/start/index.mdx
> +**There are two ways to start with Tact**: using a template or starting from scratch.
let's not overuse bold fonts

2023-10-27 09:45 UTC, anton-trunov commented on pages/start/index.mdx
> +## Getting start from template
there should not be any change here

2023-10-27 09:45 UTC, anton-trunov commented on pages/start/index.mdx
> +## Getting start from scratch
same

2023-10-27 09:45 UTC, anton-trunov commented on pages/start/index.mdx
> +> More details can find in https://github.com/tact-lang/tact
```suggestion
> More details can be found at https://github.com/tact-lang/tact
```

2023-11-30 08:05 UTC, anton-trunov commented on pages/start/index.mdx
> +## Getting start from scratch
Getting started is actually grammatically correct

2023-12-17 03:03 UTC, tactfunc commented
<3

2024-01-15 10:26 UTC, anton-trunov commented
Since there are some merge conflicts and unresolved conversations, I'm inclined to close this PR for now. Feel free to reopen it if you have some time to work on it

2024-01-15 10:26 UTC, closed without merging