add exit-codes
tact-lang/tact-docs pull request #48
Opened 2024-02-09 09:19 UTC by alirezatabatabaeian

For the [github issue](https://github.com/ton-society/grants-and-bounties/issues/406)

2024-02-21 09:51 UTC, alirezatabatabaeian commented
Hi. Any update?

2024-02-29 08:25 UTC, anton-trunov requested changes

2024-02-29 08:25 UTC, anton-trunov commented on pages/language/ref/exit-codes.mdx
1. The exit codes should be motivated. For instance, it should be explained how exit codes are observed by the Tact programmer.
2. All the mentioned phases (compute, action, Tact compute phase). Btw, there should be an explanation of what Tact compute phase is.
3. Are continuations necessary to explain stack overflows? If so, continuations must be explained more thoroughly.
4. Things like `the opcode 0 SETNUMARGS` appear without explanation. We don't assume our readers know what Fifth or FunC is.
5. All exit codes should have Tact code snippets that reproduce the exit codes.
6. Where the user is supposed to find `../build/Fireworks/tact_Firework.ts`?

2024-02-29 18:30 UTC, alirezatabatabaeian commented on pages/language/ref/exit-codes.mdx
1- explanation added
2- explanation added
3- explanation added
4- explanation added
5- Added
6- Corrected

2024-03-01 08:35 UTC, closed without merging